---
      
- name: Installing system packages
  hosts: all
  tasks:
    - import_tasks: tasks/install_dependencies.yml
      tags:
        - system

- name: Several global administration tasks
  hosts: all
  tasks:
    - import_tasks: tasks/global_administration.yml
      vars:
        hostname: "{{ host_name }}"
      tags:
        - system



    #- firewalld: port=2223-65535/tcp permanent=true state=enabled
    #  become: yes

    #- name: "Allow HTTPS"
    #  firewalld:
    #    service: https
    #    permanent: true
    #    state: enabled
    #  become: yes

    #- name: "Allow HTTP"
    #  firewalld:
    #    service: https
    #    permanent: true
    #    state: enabled
    #  become: yes
  
#- name: Installing Jenkins
#  hosts: all
#  vars:
#    jenkins_version: '{{ version_jenkins }}'
#    jenkins_package_state: "present"
#    jenkins_http_port: '{{ port_jenkins }}'
#    jenkins_admin_username: '{{ user_jenkins }}'
#    jenkins_admin_password: '{{ password_jenkins }}'
#    jenkins_plugins: ["cloverphp", "cobertura", "docker-workflow", "embeddable-build-status", "jdepend", "analysis-collector", "xunit", "violations"]
#  roles:
#    - role: geerlingguy.jenkins
#      become: true
#  tasks:
#    - import_tasks: tasks/install_dev_tools.yml
#  tags:
#    - development

- name: "Creating services"
  hosts: all
  tasks:
    - import_tasks: tasks/install_services.yml
  tags:
    - services

- name: "Importing data and configuring services"
  hosts: balin
  tasks:
  - import_tasks: tasks/services/data/piwigo.yml
  - import_tasks: tasks/services/configuration/piwigo.yml
  - import_tasks: tasks/services/data/nextcloud.yml
  tags:
    - services
    - configuration
  roles:
  - reverseproxy
