- hostname:
    name: "{{ hostname }}"
  become: yes

- name: Remove Root SSH Configuration
  file: path=/root/.ssh state=absent
  sudo: yes

- name: Remove root ssh login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  become: yes

- name: Remove password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  become: yes

- name: Remove password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: 'X11Forwarding no'
  become: yes

- name: Reload sshd condig
  command: service ssh reload
  become: yes

# Only set authorization if we are on development mode
- name: Set authorized key took from file
  authorized_key:
    user: "{{ansible_ssh_user}}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
  when:
    - ansible_ssh_user == "vagrant"
  become: yes
